# Generated by Django 4.0.2 on 2022-02-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200, null=True)),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WalletWithTokenOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_on_blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TokenOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchain')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='blockchains',
            field=models.ManyToManyField(through='core.TokenOnBlockchain', to='core.Blockchain'),
        ),
    ]
