# Generated by Django 4.0.2 on 2022-02-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='address',
        ),
        migrations.AddField(
            model_name='tokenonblockchain',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
