# Generated by Django 4.0.3 on 2022-03-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provider_providerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='blockchain',
            name='nft_explorer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('details', models.JSONField()),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFTs', to='core.blockchain')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFTs', to='core.nftcategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NFTs', to='core.wallet')),
            ],
            options={
                'unique_together': {('token_id', 'category')},
            },
        ),
    ]
