# Generated by Django 4.0.2 on 2022-02-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_token_address_tokenonblockchain_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletwithtokenonblockchain',
            name='token_on_blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tokenonblockchain'),
        ),
        migrations.CreateModel(
            name='WalletHistoryWithTokenOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.CharField(max_length=200)),
                ('wallet_with_token_on_blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.walletwithtokenonblockchain')),
            ],
        ),
    ]
