# Generated by Django 4.0.2 on 2022-02-06 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_walletwithtokenonblockchain_token_on_blockchain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenonblockchain',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_on_blockchains', to='core.token'),
        ),
        migrations.AlterField(
            model_name='wallethistorywithtokenonblockchain',
            name='wallet_with_token_on_blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.walletwithtokenonblockchain'),
        ),
        migrations.AlterField(
            model_name='walletwithtokenonblockchain',
            name='token_on_blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.tokenonblockchain'),
        ),
        migrations.AlterField(
            model_name='walletwithtokenonblockchain',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_on_blockchains', to='core.wallet'),
        ),
        migrations.CreateModel(
            name='TokenPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.token')),
            ],
        ),
    ]
