# Generated by Django 4.0.2 on 2022-02-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tokenonblockchain_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistorywithtokenonblockchain',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
