# Generated by Django 4.0.3 on 2022-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wallethistorywithtokenonblockchain_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='explorer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tokenonblockchain',
            unique_together={('blockchain', 'token')},
        ),
        migrations.AlterUniqueTogether(
            name='tokenpricehistory',
            unique_together={('token', 'timestamp', 'price')},
        ),
        migrations.AlterUniqueTogether(
            name='wallethistorywithtokenonblockchain',
            unique_together={('wallet_with_token_on_blockchain', 'timestamp', 'balance')},
        ),
        migrations.AlterUniqueTogether(
            name='walletwithtokenonblockchain',
            unique_together={('token_on_blockchain', 'wallet')},
        ),
    ]
