# Generated by Django 4.0.3 on 2022-03-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('decimals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_on_blockchains', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('explorer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WalletWithAssetOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_on_blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='core.assetonblockchain')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_on_blockchains', to='core.wallet')),
            ],
            options={
                'unique_together': {('asset_on_blockchain', 'wallet')},
            },
        ),
        migrations.AddField(
            model_name='assetonblockchain',
            name='blockchain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blockchain'),
        ),
        migrations.AddField(
            model_name='asset',
            name='blockchains',
            field=models.ManyToManyField(through='core.AssetOnBlockchain', to='core.blockchain'),
        ),
        migrations.CreateModel(
            name='WalletHistoryWithAssetOnBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.CharField(max_length=200)),
                ('manual', models.BooleanField(default=False)),
                ('wallet_with_asset_on_blockchain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.walletwithassetonblockchain')),
            ],
            options={
                'unique_together': {('wallet_with_asset_on_blockchain', 'timestamp', 'balance')},
            },
        ),
        migrations.CreateModel(
            name='AssetPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.asset')),
            ],
            options={
                'unique_together': {('asset', 'timestamp', 'price')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assetonblockchain',
            unique_together={('blockchain', 'asset')},
        ),
    ]
