# Generated by Django 4.0.3 on 2022-03-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('path', models.CharField(max_length=200)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Registered'), (2, 'Active'), (3, 'Paused'), (4, 'Not found')], default=1)),
                ('configuration', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ProviderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(auto_now_add=True)),
                ('error', models.CharField(max_length=200, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.provider')),
            ],
        ),
    ]
