# Generated by Django 4.0.3 on 2022-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nftcategory_blockchain_nft_explorer_nft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
