# Generated by Django 4.0.3 on 2022-04-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
