# Generated by Django 4.0.3 on 2022-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nft_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='asset',
            name='last_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_24h_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AssetPriceHistory',
        ),
    ]
