# Generated by Django 4.0.3 on 2022-06-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_nft_options_asset_last_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_run_end_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_run_error',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_run_start_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='ProviderHistory',
        ),
    ]
